### ISSUE TITLE
README page needed

### ISSUE THREAD

**Issue by D5D0Ds** [PaLangCODE/Styaapan#2]
@piyushalankar251 Please create a README for the repo and add all steps to run the web app in the local system.

**Comment by opeolluwa** [comment]
Hello there 👋
I would like to help with the documentation but then, I need an overview of the workings of the project. It's about, its features and how to use it.

**Comment by D5D0Ds** [comment]
> Hello there 👋 I would like to help with the documentation but then, I need an overview of the workings of the project. It's about, its features and how to use it.

It's going to be updated in the next few hours. Watch out for this repo's Wiki page and README in a few hours😁!

**Comment by Drexter-07** [comment]
Completed the readme file
